### ISSUE TITLE
Problème courbe

### ISSUE THREAD

**Issue by matthie-u** [emilienschultz/dstool#5]
Bonjour, 
Nous avons un problème pour tracer la courbe chronologique. Nous avons réussi à convertir le fichier europresse de html à cdv et nous avons renommé la colonne Date_mod en Date. Néanmoins au moment d'afficher la courbe, il est affiché ceci : 

<img width="691" alt="Capture d’écran 2023-10-14 à 17 27 44" src="https://github.com/emilienschultz/dstool/assets/147935006/aa8e1bcd-59c9-4a84-9937-4e0eb48d1eba">

Pourtant, la ligne évoquée n'est pas différente des autres dans le fichier... 

D'avance merci pour votre aide, 

Matthieu

**Comment by emilienschultz** [comment]
Vous m'envoyez le fichier concerné à mon adresse email sciencespo ?

(c'est super d'avoir ouvert une issue sur Github, c'est le début d'une collaboration open source :)
