### ISSUE TITLE
Convertisseur

### ISSUE THREAD

**Issue by justinebabin** [emilienschultz/dstool#6]
Bonjour, je parviens à convertir un fichier html en csv grâce à dstool mais ce csv n'est pas organisé par colonnes (toutes les infos du corpus europresse sont rassemblées dans la même colonnes). En conséquence, cela me bloque pour transformer le csv en graphique temporel. J'obtiens une notification d'erreur (comme Matthieu)

**Comment by emilienschultz** [comment]
Vous m'envoyez le fichier à mon adresse sciencespo ? Je pense que le problème est uniquement lié à
l'ouverture du fichier CSV dans votre tableur (excel je pense), sans
spécifier que le séparateur est la virgule ",". Donc quand vous l'ouvrez, il ne voit pas la séparation et a l'impression d'avoir une seule colonne, mais c'est juste l'affichage. Pour préciser le type de
séparateur : https://www.ablebits.com/office-addins-blog/convert-csv-excel/

Le sam. 14 oct. 2023 à 17:52, justinebabin ***@***.***> a
écrit :

**Comment by justinebabin** [comment]
je ne peux pas joindre le doc html sur github apparemment mais voilà le fichier csv : 
[tableau CSV extrait de l'essai 3 html europresse (vidéo 4).csv](https://github.com/emilienschultz/dstool/files/12906662/tableau.CSV.extrait.de.l.essai.3.html.europresse.video.4.csv)

J'ai essayé de l'enregistrer sur mon ordinateur au format csv virgule et point virgule mais il semble que le problème vienne d'ailleurs.

**Comment by justinebabin** [comment]
Je vous le renvoie par mail, je n'avais pas vu, désolée !

**Comment by emilienschultz** [comment]
Répondu par mail. Je clos pour le moment ce billet, si le problème revient, n'hésitez pas à le rouvrir.
