### ISSUE TITLE
Conversion d'un fichier html d'Europresse en format csv

### ISSUE THREAD

**Issue by carolinessap** [emilienschultz/dstool#7]
Bonjour Monsieur Schultz, 

Merci beaucoup d'avoir créé cet espace d'échange pour résoudre nos problèmes!

En sélectionnant un corpus html téléchargé sur Europresse pour le convertir en format csv, une erreur s'affiche. Je ne rencontre pas ce problème lorsque je sélectionne un seul lien html, mais cela ne me permet pas de traiter un corpus sur OpenRefine après.

Pourriez-vous m'aider à trouver mon erreur, s'il vous plaît?

Je vous envoie en pièce jointe les captures d'écran, à défaut de réussir à les insérer directement dans cette issue.

Merci beaucoup pour votre aide!

Bien cordialement,

Caroline Sasaki-Pericou

**Comment by carolinessap** [comment]
[capture d'écran destool.docx](https://github.com/emilienschultz/dstool/files/12909079/capture.d.ecran.destool.docx)

**Comment by emilienschultz** [comment]
est-ce que vous pouvez m'envoyer par mail les fichiers html utilisés initialement ?
(et c'est super d'avoir ouvert une issue, c'est la première étape vers la collaboration open source :)

**Comment by emilienschultz** [comment]
Le problème était du côté du service. Je pense l'avoir corrigé. Certaines sources non journalistiques (comme Reports - Agrobusiness - MAAF) sont difficiles à prendre en compte. Pour le moment elles sont ignorées dans le tableau (à avoir en tête). Dites moi si vous avez toujours le problème.

**Comment by emilienschultz** [comment]
Je clos pour le moment ce billet, si le problème revient, n'hésitez pas à le rouvrir.
